// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "KolinMarket/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockOrderRepository) GetByID(ctx context.Context, id string) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderRepository)(nil).GetByID), ctx, id)
}

// ListByCustomer mocks base method.
func (m *MockOrderRepository) ListByCustomer(ctx context.Context, customerID, cursor string, limit int) ([]*domain.Order, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCustomer", ctx, customerID, cursor, limit)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByCustomer indicates an expected call of ListByCustomer.
func (mr *MockOrderRepositoryMockRecorder) ListByCustomer(ctx, customerID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCustomer", reflect.TypeOf((*MockOrderRepository)(nil).ListByCustomer), ctx, customerID, cursor, limit)
}

// SaveWithEvent mocks base method.
func (m *MockOrderRepository) SaveWithEvent(ctx context.Context, order *domain.Order, eventType string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithEvent", ctx, order, eventType, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWithEvent indicates an expected call of SaveWithEvent.
func (mr *MockOrderRepositoryMockRecorder) SaveWithEvent(ctx, order, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithEvent", reflect.TypeOf((*MockOrderRepository)(nil).SaveWithEvent), ctx, order, eventType, payload)
}

// UpdateStatusWithEvent mocks base method.
func (m *MockOrderRepository) UpdateStatusWithEvent(ctx context.Context, order *domain.Order, eventType string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithEvent", ctx, order, eventType, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithEvent indicates an expected call of UpdateStatusWithEvent.
func (mr *MockOrderRepositoryMockRecorder) UpdateStatusWithEvent(ctx, order, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithEvent", reflect.TypeOf((*MockOrderRepository)(nil).UpdateStatusWithEvent), ctx, order, eventType, payload)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// SaveOrderWithEvent mocks base method.
func (m *MockOutboxRepository) SaveOrderWithEvent(ctx context.Context, order *domain.Order, eventType string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrderWithEvent", ctx, order, eventType, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrderWithEvent indicates an expected call of SaveOrderWithEvent.
func (mr *MockOutboxRepositoryMockRecorder) SaveOrderWithEvent(ctx, order, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrderWithEvent", reflect.TypeOf((*MockOutboxRepository)(nil).SaveOrderWithEvent), ctx, order, eventType, payload)
}
